version: '3.4'

x-backend:
  &backend
  build:
    context: .
    dockerfile: Dockerfile.dev
  env_file: .env
  environment:
    RAILS_ENV: development
    REDIS_URL: redis://redis:6379/1
  restart: on-failure:3
  stdin_open: true
  tty: true
  volumes:
    - .:/backend:rw
    - bundle_cache:/bundle

services:
  backend:
    <<: *backend
    ports:
      - 3000:3000/tcp
    depends_on:
      - db

  db:
    image: postgres:11.2
    env_file: .env
  #  environment:
  #    POSTGRES_USER: postgres
  #    POSTGRES_PASSWORD: secret
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq
    depends_on:
      - redis
      - backend

  redis:
    image: 'redis:6.2.13-alpine'
    #image: 'redis:5.0-alpine'
    command: redis-server
    volumes:
      - redis:/data

volumes:
  bundle_cache:
  postgres:
  redis:

