version: '3'


services:
  backend:
    image: cirobessa/rails-backend
    ports:
      - 3000:3000/tcp
    env_file: .env
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis

  db:
    image: postgres:11.2
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

  sidekiq:
    image: cirobessa/rails-backend
    command: bundle exec sidekiq
    depends_on:
      - redis
      - backend
      - db
    env_file: .env
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1

  redis:
    image: 'redis:6.2.13-alpine'
    command: redis-server
    ports:
      - "6379:6379"

volumes:
  postgres:
  db_data:

