name: Rails Container Build and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v3
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build Docker image
        run: |
          docker build -t cirobessa/rails-backend:${{ github.sha }} .
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push cirobessa/rails-backend:${{ github.sha }}

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: latest # Adjust as needed

      - name: Deploy to Kubernetes
        run: |
          aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.DOCKERHUB_TOKEN }}
          aws eks list-clusters | grep  ${{ secrets.DOCKER_USER }} | sed s/\"//g
          cd k8s-manifests
          kubectl create -f backend-deployment.yaml,backend-service.yaml,db-deployment.yaml,db-service.yaml,env-configmap.yaml,postgres-persistentvolumeclaim.yaml,redis-deployment.yaml,redis-service.yaml,secret.yaml,sidekiq-deployment.yaml

